# Generated by Django 5.0.2 on 2025-04-19 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_creditscorehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscorehistory',
            name='date',
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='credit_utilization',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='dti',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
