# Generated by Django 5.0.2 on 2025-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_creditscorehistory_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditscorehistory',
            old_name='timestamp',
            new_name='date',
        ),
    ]
