export const SIGNUP_PROJECT_REQUEST= "SIGNUP_PROJECT_REQUEST" 
export const SIGNUP_PROJECT_SUCCESS= "SIGNUP_PROJECT_SUCCESS" 
export const SIGNUP_PROJECT_FAIL= "SIGNUP_PROJECT_FAIL" 

export const LOGIN_PROJECT_REQUEST= "LOGIN_PROJECT_REQUEST" 
export const LOGIN_PROJECT_SUCCESS= "LOGIN_PROJECT_SUCCESS" 
export const LOGIN_PROJECT_FAIL= "LOGIN_PROJECT_FAIL"

export const LOGOUT_PROJECT= "LOGOUT_PROJECT"

export const GET_USERDETAIL_REQUEST='GET_USERDETAIL_REQUEST'
export const GET_USERDETAIL_SUCCESS='GET_USERDETAIL_SUCCESS'
export const GET_USERDETAIL_FAIL='GET_USERDETAIL_FAIL'

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';


export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL';

export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST'
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS'
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL'

export const FETCH_CREDIT_SCORE_HISTORY='FETCH_CREDIT_SCORE_HISTORY'


